# Mandatory
server:
  port: 6002

# Mandatory.
cache:
  host: "0.0.0.0"
  port: 0000
  ttl: "PT10M"
  # Optional. Default is 0.
  db: 0

# Optional.
responseCache:
  mongoURL: "mongodb://xxxx:xxxxx@0.0.0.0/xxxx?authSource=admin"
  ttl: "PT10M"

# Mandatory.
# Priority order will be
# 1. Synchronous
# 2. webhook
# 3. pubSub
client:
  # synchronous:
  #   mongoURL: "mongodb://127.0.0.1:27017/protocolserver-v2-response-cache"

  webhook:
    url: "https://xxx.xxxxxx.com"

  #messageQueue:
  #  amqpURL: "amqp://guest:guest@localhost:5672"
  #  incomingQueue: "protocol-server-incoming"
  #  outgoingQueue: "protocol-server-outgoing"

# Mandatory.
app:
  # Mandatory.
  mode: bpp

  # Two types of gateway mode present.
  # client and network.
  gateway:
    mode: network
    inboxQueue: "xxxx"
    outboxQueue: "xxxx"
    amqpURL: "amqp://xxx:xxxx@0.0.0.0:0000"

  # Mandatory.
  actions:
    requests:
      search:
        ttl: "PT20S"
      init:
        ttl: "PT20S"
      select:
        ttl: "PT20S"
      confirm:
        ttl: "PT20S"
      status:
        ttl: "PT20S"
      get_cancellation_reasons:
        ttl: "PT20S"
      get_rating_categories:
        ttl: "PT20S"

    responses:
      on_search:
        ttl: "PT20S"
      on_init:
        ttl: "PT20S"
      on_select:
        ttl: "PT20S"
      on_confirm:
        ttl: "PT20S"
      on_status:
        ttl: "PT20S"
      cancellation_reasons:
        ttl: "PT20S"
      rating_categories:
        ttl: "PT20S"

  # Mandatory.
  privateKey: "xxxx"
  publicKey: "xxxx"

  # Mandatory.
  subscriberId: "xxxx"
  subscriberUri: "xxxx"

  # Mandatory.
  registryUrl: "xxxx"
  auth: false
  uniqueKey: "xxxx"

  # Mandatory.
  city: "xxxx"
  country: "xxxx"

  # Mandatory.
  ttl: "PT10M"

  # Mandatory.
  httpTimeout: "PT3S"
  httpRetryCount: 0