# Mandatory
server:
  port: 6002

# Mandatory.
cache:
  host: "3.111.144.76"
  port: 6379
  ttl: "PT10M"
  # Optional. Default is 0.
  db: 0

# Optional.
responseCache:
  mongoURL: "mongodb://tvast:password@3.111.144.76/protocolserver-v2-response-cache?authSource=admin"
  ttl: "PT10M"

# Mandatory.
# Priority order will be
# 1. Synchronous
# 2. webhook
# 3. pubSub
client:
  # synchronous:
  #   mongoURL: "mongodb://127.0.0.1:27017/protocolserver-v2-response-cache"

  webhook:
    url: "https://webhooksandbox.buildononest.com"

  #messageQueue:
  #  amqpURL: "amqp://guest:guest@localhost:5672"
  #  incomingQueue: "protocol-server-incoming"
  #  outgoingQueue: "protocol-server-outgoing"

# Mandatory.
app:
  # Mandatory.
  mode: bpp

  # Two types of gateway mode present.
  # client and network.
  gateway:
    mode: network
    inboxQueue: "inbox-bpp"
    outboxQueue: "outbox-bpp"
    amqpURL: "amqp://tvast:password@3.111.144.76:5672"

  # Mandatory.
  actions:
    requests:
      search:
        ttl: "PT20S"
      init:
        ttl: "PT20S"
      select:
        ttl: "PT20S"
      confirm:
        ttl: "PT20S"
      status:
        ttl: "PT20S"
      get_cancellation_reasons:
        ttl: "PT20S"
      get_rating_categories:
        ttl: "PT20S"

    responses:
      on_search:
        ttl: "PT20S"
      on_init:
        ttl: "PT20S"
      on_select:
        ttl: "PT20S"
      on_confirm:
        ttl: "PT20S"
      on_status:
        ttl: "PT20S"
      cancellation_reasons:
        ttl: "PT20S"
      rating_categories:
        ttl: "PT20S"

  # Mandatory.
  privateKey: "QsFchiZU2GU1g8KhYi6JFa8TW6KQp593CJzN75vk8kkqyAUKCyLx3vnl42ciAsT5PDOjBfv2F0gy+1YHQii29A=="
  publicKey: "KsgFCgsi8d755eNnIgLE+TwzowX79hdIMvtWB0IotvQ="

  # Mandatory.
  subscriberId: "soal-bpp"
  subscriberUri: "https://soal-onest-bpp-network.onrender.com/"

  # Mandatory.
  registryUrl: "https://registry.becknprotocol.io/subscribers"
  auth: false
  uniqueKey: "soal-bap.key"

  # Mandatory.
  city: "std:080"
  country: "IND"

  # Mandatory.
  ttl: "PT10M"

  # Mandatory.
  httpTimeout: "PT3S"
  httpRetryCount: 2